#!/bin/bash

# Usage: mfa2 AWS_SOURCE_PROFILE AWS_USERNAME ONE_TIME_PASSWORD


AWS_SOURCE_PFOFILE="$1"
AWS_USERNAME="$2"
TOKEN="$3"
AWS_OUTPUT_PROFILE="${AWS_SOURCE_PFOFILE}_MFA"

MFA_SERIAL=$(AWS_PROFILE="$AWS_SOURCE_PFOFILE" aws iam list-mfa-devices --user-name="$AWS_USERNAME" --query 'MFADevices[0].SerialNumber')

# remove trailing double quote
MFA_SERIAL="${MFA_SERIAL%\"}"

# remove leading double quote
MFA_SERIAL="${MFA_SERIAL#\"}"
RESPONSE=$(AWS_PROFILE="$AWS_SOURCE_PFOFILE" aws sts get-session-token --serial-number "$MFA_SERIAL" --token-code "$TOKEN" --output json)

# jq -r is the raw output without quotes
_AWS_ACCESS_KEY_ID=$(echo "$RESPONSE" | jq -r '.Credentials.AccessKeyId')
_AWS_SECRET_ACCESS_KEY=$(echo "$RESPONSE" | jq -r '.Credentials.SecretAccessKey')
_AWS_SESSION_TOKEN=$(echo "$RESPONSE" | jq -r '.Credentials.SessionToken')
_AWS_ACCESS_KEY_ID_EXPIRATION=$(echo "$RESPONSE" | jq -r '.Credentials.Expiration')

aws configure --profile "$AWS_OUTPUT_PROFILE" set region us-east-1
aws configure --profile "$AWS_OUTPUT_PROFILE" set aws_access_key_id "$_AWS_ACCESS_KEY_ID"
aws configure --profile "$AWS_OUTPUT_PROFILE" set aws_secret_access_key "$_AWS_SECRET_ACCESS_KEY"
aws configure --profile "$AWS_OUTPUT_PROFILE" set aws_session_token "$_AWS_SESSION_TOKEN"

if [ $? -ne 0 ]
then
	echo "Something went wrong, please check your parameters and try again. The $AWS_OUTPUT_PROFILE profile have not been updated."
else
	echo "Your MFA AWS credentials have been saved to the $AWS_OUTPUT_PROFILE profile. Expiration: $_AWS_ACCESS_KEY_ID_EXPIRATION"
fi
