---
- name: Install system
  hosts: 127.0.0.1
  become: true

  tasks:
          #    - name: 'Upgrade system'
          #      pacman:
          #        upgrade: yes
          #        state: latest

    - name: 'Create user for aur command'
      user:
        name: aur_builder
        group: wheel

    - name: 'Add entry about aur_builder user in sudoers'
      lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'

    - name: 'Install Pacaur'
      pacman:
        name: pacaur
        state: latest

    - name: 'Install traceroute'
      pacman:
        name: traceroute
        state: latest

    - name: 'Install jq'
      pacman:
        name: jq
        state: latest

    - name: 'Install CLion'
      aur: name=clion use=makepkg skip_installed=true
      become: yes
      become_user: aur_builder

    - name: 'Install PHPStorm'
      aur: name=phpstorm use=makepkg skip_installed=true
      become: yes
      become_user: aur_builder

    - name: 'Install Skype'
      aur: name=skypeforlinux-stable-bin use=makepkg skip_installed=true use=pacaur
      become: yes
      become_user: aur_builder

    - name: 'Install terraform'
      pacman:
        name: terraform
        state: latest

    - name: 'Install xrandr GUI'
      pacman:
        name: arandr
        state: present

    - name: 'Install Firefox'
      pacman:
        name: firefox
        state: present

    - name: 'Install chrome'
      aur: name=google-chrome use=makepkg skip_installed=true
      become: yes
      become_user: aur_builder

    - name: 'Install Meld'
      pacman:
        name: meld
        state: present

    - name: 'Install VSC'
      pacman:
        name: code
        state: present

    - name: 'Install Docker'
      pacman:
        name: docker,docker-compose
        state: latest

    - name: 'Install aws-cli'
      pacman:
        name: aws-cli
        state: latest

    - name: 'Install Transmission'
      pacman:
        name: transmission-qt
        state: present

    - name: 'Install MasterPDFEditor'
      aur: name=masterpdfeditor use=makepkg skip_installed=true
      become: yes
      become_user: aur_builder

    - name: 'Install keepass'
      pacman:
        name: keepassxc
        state: present

    - name: 'Install npm'
      pacman:
        name: npm
        state: present

    - name: 'Install youtube-dl'
      pacman:
        name: youtube-dl
        state: present

    - name: 'Install clementine'
      pacman:
        name: clementine
        state: present

    - name: 'Install PyCharm'
      aur: name=pycharm-professional use=makepkg skip_installed=true
      become: yes
      become_user: aur_builder

    - name: 'Install cloudflare CLI'
      npm:
        name: cloudflare-cli
        global: yes

    - name: 'Install Intellij IDEA'
      aur: name=intellij-idea-ce use=makepkg skip_installed=true
      become: yes
      become_user: aur_builder

    - name: 'Install Calibre'
      aur: name=calibre use=makepkg skip_installed=true
      become: yes
      become_user: aur_builder



    - import_tasks: install-pritunl-client.yml
    - import_tasks: install-nginx.yml
    - import_tasks: git-config.yml
